spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true # 允许bean对象覆盖
  #  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/db_ruiji
#      username: root
#      password: 8787521
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.59.130:3306/master_db
        username: zisheng
        password: 8787521
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master_db
        username: zisheng
        password: 8787521
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin # 轮询
      # 最终的数据源名称
      name: datasource
      # 主数据源名称
      master-data-source-name: master
      # 从数据源名称，多个的话采用逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true # 开启sql提示
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 100MB
  redis:
    host: localhost
    port: 6379
    password: 8787521
    database: 0
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: 1ms
        max-active: 8
  cache:
    redis:
      time-to-live: 300000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: off
    db-config:
      # 设置进行表映射的时候，自动加上tb_前缀
#      table-prefix: tb_
      # 配置主键生成策略,采用雪花算法，生成的是一个64位的值，需要用Long类型去存储
      id-type: assign_id
signKey: zisheng
# 配置文件路径
File:
  url: D:/image/
# Spring事务管理日志记录开关
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

